version: '3.3'
services:
  postgres:
    image: postgres:10
    container_name: postgres
    environment:
      - POSTGRES_DB=fastfood-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - TZ=GMT
    ports:
      - 5432:5432